# Generated by Django 2.1.3 on 2018-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='user',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='amount',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
